spring:
  profiles: prod
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    database-name: glass_prod
    url: jdbc:mysql://localhost:3306/glass_prod
    username: root
    password: qnlpkuge
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
  thymeleaf: 
    cache: true
    
logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    org.springframework.data: ERROR
    com.goosun.glass: INFO