spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    database-name: glass
    url: jdbc:mysql://localhost:3306/glass?useSSL=false
    username: root
    password: qnlpkuge
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  session:
    store-type: redis

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data: INFO
    com.goosun.glass: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always