spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    database-name: glass_prod
    url: jdbc:mysql://localhost:3306/glass_prod?useSSL=false
    username: root
    password: qnlpkuge
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
  thymeleaf: 
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
  session:
    store-type: redis

logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    org.springframework.data: ERROR
    com.goosun.glass: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"