spring:
  profiles: dev
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    database-name: glass
    url: jdbc:mysql://localhost:3306/glass
    username: root
    password: qnlpkuge
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
  thymeleaf: 
    cache: false

logging:
  level:
    ROOT: DEBUG
    org.springframework: DEBUG
    org.springframework.data: DEBUG
    com.goosun.glass: INFO
