server:
  port: 9999
  session:
    timeout: 1800
    redis:
      namespace: session

spring:
  profiles:
    active: dev

    
mybatis:
  mapper-locations: classpath*:mapper/*.xml  
  type-aliases-package: com.goosun.glass.domain

mapper:
    mappers:
        - com.goosun.glass.dao
    not-empty: false
    identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true

    